### ISSUE TITLE
Allow frag data storage

### ISSUE THREAD

**Issue by DianeLooney** [DianeLooney/gvd#58]
Extra storage buffers can be set up with `glBindFragDataLocation`. Unsure of how this would be useful, perhaps for when some value needs to change over time but when the changes should be discrete.

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBindFragDataLocation.xhtml

**Comment by gwenprime** [comment]
that link is broken.
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBindFragDataLocation.xhtml

**Comment by gwenprime** [comment]
looks really cool though. I can imagine some uses i think.

**Comment by DianeLooney** [comment]
Example of such a shader would be having it display the diff of the current and previous frame of an input. This is somewhat possible without, but only with heavy screen flicker.

**Comment by DianeLooney** [comment]
Got this working with imageStore commands instead. Very WIP branch is `djl/fix-clear-issue` because I don't know how to name things properly.

**Comment by DianeLooney** [comment]
Solved with the new `storage` things
